# Generated for CSCI 3342 Project 2
from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='Slider', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('image_src', models.CharField(max_length=200)),('image_width', models.IntegerField(default=285)),('image_height', models.IntegerField(default=437)),('anchor_url', models.CharField(default='#', max_length=200)),('movie_genre', models.CharField(max_length=10)),('movie_title', models.CharField(max_length=20)),('lower_rating', models.CharField(default='7', max_length=5)),('upper_rating', models.CharField(default='/10', max_length=5))]),
        migrations.CreateModel(name='Advertisement', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('section', models.CharField(max_length=20)),('img_src', models.CharField(max_length=200)),('img_width', models.IntegerField(default=336)),('img_height', models.IntegerField(default=296))]),
        migrations.CreateModel(name='SocialLink', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name', models.CharField(max_length=50)),('anchor_class', models.CharField(blank=True, max_length=20)),('icon_class', models.CharField(max_length=30)),('url', models.CharField(max_length=200))]),
        migrations.CreateModel(name='Trailer', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('trailer_url', models.CharField(max_length=200))]),
        migrations.CreateModel(name='TrailerItem', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('img_src', models.CharField(max_length=200)),('img_alt', models.CharField(max_length=100)),('img_width', models.IntegerField(default=100)),('img_height', models.IntegerField(default=56)),('description', models.CharField(max_length=100)),('duration', models.CharField(max_length=10))]),
        migrations.CreateModel(name='Celebrity', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('anchor_url', models.CharField(default='#', max_length=200)),('img_width', models.IntegerField(default=70)),('img_height', models.IntegerField(default=70)),('celebrity_url', models.CharField(max_length=200)),('celebrity_name', models.CharField(max_length=50)),('celebrity_type', models.CharField(max_length=20))]),
        migrations.CreateModel(name='News', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('section', models.CharField(max_length=20)),('img_src', models.CharField(max_length=200)),('img_alt', models.CharField(max_length=100)),('img_width', models.IntegerField(default=170)),('img_height', models.IntegerField(default=250)),('title', models.CharField(max_length=100)),('content', models.CharField(max_length=500)),('time', models.CharField(max_length=20))]),
        migrations.CreateModel(name='Tweet', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('content', models.TextField())]),
        migrations.CreateModel(name='MovieTheater', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('type', models.CharField(max_length=20)),('img_src', models.CharField(max_length=200)),('img_width', models.IntegerField(default=185)),('img_height', models.IntegerField(default=284)),('anchor_url', models.CharField(default='#', max_length=200)),('movie_genre', models.CharField(max_length=10)),('movie_title', models.CharField(max_length=20)),('lower_rating', models.CharField(default='7', max_length=5)),('upper_rating', models.CharField(default='/10', max_length=5))]),
        migrations.CreateModel(name='MovieTV', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('type', models.CharField(max_length=20)),('img_src', models.CharField(max_length=200)),('img_width', models.IntegerField(default=185)),('img_height', models.IntegerField(default=284)),('anchor_url', models.CharField(default='#', max_length=200)),('movie_genre', models.CharField(max_length=10)),('movie_title', models.CharField(max_length=20)),('lower_rating', models.CharField(default='7', max_length=5)),('upper_rating', models.CharField(default='/10', max_length=5))]),
        migrations.CreateModel(name='NewsletterSubscriber', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('email', models.EmailField(max_length=254, unique=True)),('created_at', models.DateTimeField(auto_now_add=True))]),
    ]
