# Generated by Django 6.0.4 on 2026-04-30 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='img_src',
            field=models.CharField(default='images/uploads/ava1.jpg', max_length=200),
            preserve_default=False,
        ),
    ]
