# Generated by Django 6.0.4 on 2026-04-30 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0002_celebrity_img_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='traileritem',
            name='img_alt',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
