# Generated by Django 6.0.3 on 2026-05-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project2App', '0003_traileritem_img_alt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_subscribed', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
